# Github pages website
- name: evanpurkhiser.com
  proxied: yes
  type: CNAME
  content: evanpurkhiser.github.io
- name: www
  proxied: yes
  type: CNAME
  content: evanpurkhiser.github.io

# go-meta github page
- name: go
  proxied: yes
  type: CNAME
  content: evanpurkhiser.github.io

# IPv6 home devices
- name: server.home
  type: AAAA
  content: 2604:5500:c074:0:d250:99ff:fec2:9f08

# IPv4 home address
- name: server.home
  type: A
  content: 136.24.27.16

# Services
- name: packages
  proxied: yes
  type: CNAME
  content: server.home.evanpurkhiser.com

- name: public
  proxied: yes
  type: CNAME
  content: server.home.evanpurkhiser.com

- name: tunnel
  proxied: yes
  type: CNAME
  content: server.home.evanpurkhiser.com

- name: transmission
  proxied: yes
  type: CNAME
  content: server.home.evanpurkhiser.com

- name: resume
  proxied: yes
  type: CNAME
  content: server.home.evanpurkhiser.com

- name: avatar
  proxied: yes
  type: CNAME
  content: server.home.evanpurkhiser.com

# Keybase.io identity
- name: evanpurkhiser.com
  type: TXT
  content: keybase-site-verification=ZsPm75q4bJZXoDClgmRJ-v2z3gbjhOyKUqczEj8AiBc
