darksky_api_key: '{{ home_assistant.darksky_api_key }}'
spotify_api_key: '{{ home_assistant.spotify_api_key }}'
spotify_username: '{{ home_assistant.spotify_username }}'
spotify_password: '{{ home_assistant.spotify_password }}'
ecobee_api_key: '{{ home_assistant.ecobee_api_key }}'
telegram_bot_token: '{{ home_assistant.telegram_bot_token }}'
octoprint_api_key: '{{ home_assistant.octoprint_api_key }}'
google_assistant_service_account: {{ home_assistant.google_assistant_service_account | from_json | to_json }}
