- name: Install pam-ssh-agent
  become: true
  become_user: aur-builder
  kewlfft.aur.aur:
    name: pam-ssh-agent

- name: Configure pam.d/sudo
  ansible.builtin.copy:
    src: pam-sudo
    dest: /etc/pam.d/sudo
    mode: "0644"

- name: Add authorized public ssh-key for sudo
  ansible.posix.authorized_key:
    user: root
    path: /etc/security/authorized_keys
    key: "{{ public_ssh_key }}"
    comment: personal
